### ISSUE TITLE
Import Failed

### ISSUE THREAD

**Issue by DJLegends1011** [Kinglord/ComfyUI_LoRA_Sidebar#5]
getting this error reinstall after reinstall

**Comment by DJLegends1011** [comment]
> Traceback (most recent call last):
  File "D:\AiVid\ComfyUI\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\AiVid\ComfyUI\ComfyUI\custom_nodes\ComfyUI_LoRA_Sidebar\__init__.py", line 22, in <module>
    from dateutil import parser
ModuleNotFoundError: No module named 'dateutil'
heres log for it

**Comment by Kinglord** [comment]
That's my bad, I was fixing things and left that in there but it's not part of the standard python lib, I'll change this when I push a new version to not use that library. If you want to get it working right now you can just install that with pip and it will be fine.

**Comment by DJLegends1011** [comment]
yea tried installing via pip which was fine but the module couldn't detect it lol

**Comment by Kinglord** [comment]
Probably didn't install it into the right python environment (happens to a lot of us which is why I don't like using external libraries), in any case I'm going to close this out because I removed this dependency in the latest version.
